CREATE TABLE `VEHICULO` (
	`PLACA` varchar(7) NOT NULL,
	`COLOR` varchar(255) NOT NULL,
	`MARCA` varchar(255) NOT NULL,
	`TIPO_VEHÍCULO` varchar(255) NOT NULL,
	`CONDUCTOR` INT(20) NOT NULL,
	`PROPIETARIO` INT(20) NOT NULL,
	PRIMARY KEY (`PLACA`)
);

CREATE TABLE `CONDUCTOR` (
	`NUMERO_CEDULA` INT(20) NOT NULL AUTO_INCREMENT,
	`PRIMER_NOMBRE` varchar(255) NOT NULL,
	`SEGUNDO_NOMBRE` varchar(255),
	`APELLIDOS` varchar(255) NOT NULL,
	`DIRECCION` varchar(255) NOT NULL,
	`TELEFONO` varchar(15) NOT NULL,
	`CIUDAD` varchar(255) NOT NULL,
	PRIMARY KEY (`NUMERO_CEDULA`)
);

CREATE TABLE `PROPIETARIO` (
	`NUMERO_CEDULA` INT(20) NOT NULL AUTO_INCREMENT,
	`PRIMER_NOMBRE` varchar(255) NOT NULL,
	`SEGUNDO_NOMBRE` varchar(255),
	`APELLIDOS` varchar(255) NOT NULL,
	`DIRECCION` varchar(255) NOT NULL,
	`TELEFONO` varchar(15) NOT NULL,
	`CIUDAD` varchar(255) NOT NULL,
	PRIMARY KEY (`NUMERO_CEDULA`)
);

ALTER TABLE `VEHICULO` ADD CONSTRAINT `VEHICULO_fk0` FOREIGN KEY (`CONDUCTOR`) REFERENCES `CONDUCTOR`(`NUMERO_CEDULA`);

ALTER TABLE `VEHICULO` ADD CONSTRAINT `VEHICULO_fk1` FOREIGN KEY (`PROPIETARIO`) REFERENCES `PROPIETARIO`(`NUMERO_CEDULA`);




-- SQL INFORME
SELECT PLACA, MARCA, CONCAT(C.PRIMER_NOMBRE," ",C.SEGUNDO_NOMBRE) CONDUCTOR, CONCAT(P.PRIMER_NOMBRE," ",P.SEGUNDO_NOMBRE) PROPIETARIO FROM VEHICULO, CONDUCTOR C, PROPIETARIO P WHERE P.VEHICULO=PLACA AND C.VEHICULO=PLACA;